### ISSUE TITLE
Known issue: Won't work in Firefox 52 ESR without an about:config change

### ISSUE THREAD

**Issue by PixievoltNo1** [PikadudeNo1/RandomBookmark#3]
You'll need to change an advanced setting to get Random Bookmark From Folder working in Firefox 52 ESR, because otherwise the preferences storage that it expects to have available will be missing. Go to about:config and set webextensions.storage.sync.enabled to true. There are no known downsides to making this change.

[Learn more about about:config](https://support.mozilla.org/en-US/kb/about-config-editor-firefox)

**Comment by polyzen** [comment]
Perhaps the readme would be a better place for this?

**Comment by PixievoltNo1** [comment]
When a user clicks the "Support Site" link on a.m.o, they'll be taken directly to the issues tracker, therefore any support information I put here will be visible immediately. (Nonetheless, for 2.1 I plan to do even better and have the info directly in the extension.)

**Comment by PixievoltNo1** [comment]
With 52 ESR long dead, I've simply dropped support for it in version 2.1. Users who need their browser to support legacy extensions should find a fork of Firefox that still supports them.
